spring:
    application:
        name: blog
    datasource:
        url: jdbc:postgresql://localhost:5432/blog
        username: postgres
        password: 123 
        driver-class-name: org.postgresql.Driver  
    jpa:
        hibernate: 
            ddl-auto: update
            dialect: org.hibernate.dialect.PostgreSQLDialect
        show-sql: true
        properties: 
            hibernate:          
                format_sql: true

    web:
        resources:
            static-locations:
                - classpath:/static/
    mvc:
        static-path-pattern: /**
    mail:
        host: smtp.gmail.com
        port: 587
        username: admin-email@example.com
        password: admin-email-password
        properties:
            mail:
                smtp:
                auth: true
                starttls:
                    enable: true    

file:
  upload-dir: C:\Users\admin\Desktop\New folder\spring\blog\blog-backend\src\main\resources\static\uploads
    
server:
    port: 8082
    error:
        include-message: always
jwt:
    secret: 2+LaR6mKTpaFTMK4NKlHUQ5JgMtQFK0zGGSE/OUgJR8oU7Vhihb0gA8RofYlZZ/30kN+My5iIvuvYPDDMld5hg==
    expiration: 36000
